sudo: required
dist: trusty
language: cpp
before_install:
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends build-essential texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended texlive-generic-recommended latex-xcolor
script:
- cd docs/Miolink/latex
- make 
- cd ../../Unity/latex
- make
